'use strict';

const API_URL = 'https://script.google.com/macros/s/AKfycbwnLkmfLiIyrV4BdDGUhjtXM7ASM0XWDvSDbgDF0lfiNrf9q0URxt09BdH7gjWDDdpI/exec';
const DEMO_MODE = API_URL.includes('PEGAR_AQUI_URL_DE_GOOGLE_APPS_SCRIPT');
const DEMO_KEY = 'michoacana_demo_v1';
const money = new Intl.NumberFormat('es-MX', { style: 'currency', currency: 'MXN', maximumFractionDigits: 2 });
const dateTime = new Intl.DateTimeFormat('es-MX', { dateStyle: 'medium', timeStyle: 'short' });
const $ = (selector, root = document) => root.querySelector(selector);
const $$ = (selector, root = document) => [...root.querySelectorAll(selector)];

const initialProducts = [
  ['TR001','Coco','Trol',35,18,10,5,12,'🥥'],['TR002','Elote','Trol',35,18,8,5,12,'🌽'],
  ['TR003','Fresa','Trol',35,18,3,5,12,'🍓'],['TR004','Galleta','Trol',35,18,7,5,12,'🍪'],
  ['TR005','Oreo','Trol',35,18,2,5,12,'🍪'],['TR006','Uva','Trol',35,18,9,5,12,'🍇'],
  ['TR007','Chocolate','Trol',35,18,6,5,12,'🍫'],['TR008','Mango c/chamoy','Trol',35,18,12,5,12,'🥭'],
  ['TR009','Piña c/chamoy','Trol',35,18,5,5,12,'🍍'],['TR010','Limón c/chamoy','Trol',35,18,4,5,12,'🍋'],
  ['TR011','Tamarindo c/chamoy','Trol',35,18,6,5,12,'🌶️'],['TR012','Guanábana','Trol',35,18,8,5,12,'🍈'],
  ['TR013','Sandía','Trol',35,18,0,5,12,'🍉'],['TR014','Chicle','Trol',35,18,7,5,12,'🍬'],
  ['OT001','Fresas con crema','Otro',45,25,5,3,8,'🍓'],['OT002','Bolsas de hielo','Otro',10,5,10,4,15,'🧊']
].map(([productoId,nombre,categoria,precioVenta,precioCompra,stock,stockMinimo,stockIdeal,emoji]) => ({ productoId,nombre,categoria,precioVenta,precioCompra,stock,stockMinimo,stockIdeal,emoji,activo:true,ventasUltimos30Dias:0 }));

let state = { products: [], sales: [], orders: [], movements: [], sellers: [], receivables: [], payments: [], config: { nombreNegocio:'La Michoacana', mensajeWhatsApp:'¡Sabor que te enamora!', moneda:'MXN' }, dashboard:null, statistics:null };
let saleCart = {};
let orderCart = {};
let historyPeriod = 'today';
let confirmResolver = null;

document.addEventListener('DOMContentLoaded', init);

async function init() {
  $('#demoBadge').hidden = !DEMO_MODE;
  bindEvents();
  await refreshAll();
}

function bindEvents() {
  $$('.bottom-nav button').forEach(btn => btn.addEventListener('click', () => navigate(btn.dataset.view)));
  $$('[data-go]').forEach(btn => btn.addEventListener('click', () => navigate(btn.dataset.go)));
  $('#quickEntry').addEventListener('click', openInventoryEntry);
  $('#inventoryEntryBtn').addEventListener('click', openInventoryEntry);
  $('#quickShare').addEventListener('click', openShare);
  $('#registerSaleBtn').addEventListener('click', registerSale);
  $('#undoSaleBtn').addEventListener('click', undoLastSale);
  $('#inventorySearch').addEventListener('input', renderInventory);
  $('#generateOrderBtn').addEventListener('click', () => generarPedidoPorPresupuesto(Number($('#budgetInput').value)));
  $('#budgetInput').addEventListener('input', updateOrderSummary);
  $('#createOrderBtn').addEventListener('click', createOrder);
  $('#shareOrderBtn').addEventListener('click', () => shareOrderByWhatsApp());
  $('#ordersHistoryBtn').addEventListener('click', openOrders);
  $('#modalClose').addEventListener('click', closeModal);
  $('#modalBackdrop').addEventListener('click', e => { if (e.target === $('#modalBackdrop')) closeModal(); });
  $('#confirmCancelBtn').addEventListener('click',()=>resolveConfirmation(false));
  $('#confirmAcceptBtn').addEventListener('click',()=>resolveConfirmation(true));
  $('#confirmBackdrop').addEventListener('click',e=>{if(e.target===$('#confirmBackdrop'))resolveConfirmation(false)});
  $('#historyFilters').addEventListener('click', e => { if (!e.target.dataset.period) return; historyPeriod=e.target.dataset.period; $$('#historyFilters button').forEach(b=>b.classList.toggle('active',b===e.target)); $('#customDates').hidden=historyPeriod!=='custom'; if(historyPeriod==='custom'){const today=localDateValue(new Date());if(!$('#dateFrom').value)$('#dateFrom').value=today;if(!$('#dateTo').value)$('#dateTo').value=today;$('#historyRangeCaption').textContent='Selecciona las fechas y pulsa Aplicar';}else{renderHistory();updateHistoryCaption();} });
  $('#applyDates').addEventListener('click',()=>{const from=$('#dateFrom').value,to=$('#dateTo').value;if(!from||!to)return toast('Selecciona ambas fechas',true);if(from>to)return toast('La fecha inicial no puede ser posterior a la final',true);renderHistory();updateHistoryCaption()});
}

async function apiRequest(action, data = {}) {
  if (DEMO_MODE) return demoApi(action, data);
  try {
    const response = await fetch(API_URL, { method:'POST', headers:{ 'Content-Type':'text/plain;charset=utf-8' }, body:JSON.stringify({ action, ...data }), redirect:'follow' });
    if (!response.ok) throw new Error(`HTTP ${response.status}`);
    const result = await response.json();
    if (!result.success) throw new Error(result.message || 'La operación no se completó');
    return result;
  } catch (error) {
    console.error(`API ${action}:`, error);
    throw new Error('No se pudo conectar con el sistema. Intenta nuevamente.');
  }
}

async function refreshAll(showLoader = true) {
  setLoading(showLoader);
  try {
    const result = await apiRequest('getDashboard');
    state = { ...state, ...result.data };
    renderAll();
  } catch (error) { toast(error.message, true); }
  finally { setLoading(false); }
}

function renderAll() { renderDashboard(); renderSellers(); renderSaleProducts(); renderInventory(); renderHistory(); renderPeriodStatistics(); renderReceivables(); }
function renderSellers(){const current=$('#sellerSelect').value;const sellers=(state.sellers||[]).filter(s=>typeof s==='string'||s.activo).map(s=>typeof s==='string'?s:s.nombre);const values=sellers.length?sellers:['Mamá','Miri','Papá','Rodrigo','Gloria'];$('#sellerSelect').innerHTML=values.map(name=>`<option>${escapeHtml(name)}</option>`).join('');if(values.includes(current))$('#sellerSelect').value=current}
function stockStatus(p) { return p.stock <= 0 ? 'out' : p.stock <= p.stockMinimo ? 'low' : 'normal'; }
function statusLabel(p) { return stockStatus(p)==='out'?'Agotado':stockStatus(p)==='low'?'Stock bajo':'Normal'; }
function escapeHtml(value='') { return String(value).replace(/[&<>'"]/g, c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c])); }

function renderDashboard() {
  const d = state.dashboard || calculateDashboard();
  $('#dashboardCards').innerHTML = [
    ['💰','Ventas de hoy',money.format(d.ventasHoy)],['🍧','Productos vendidos',d.productosVendidosHoy],
    ['📦','Unidades disponibles',d.productosDisponibles],['⚠️','Con poco stock',`${d.productosBajoStock} productos`]
  ].map(x=>`<article class="metric-card"><div class="icon">${x[0]}</div><span>${x[1]}</span><strong>${x[2]}</strong></article>`).join('');
  const lows=state.products.filter(p=>p.stock<=p.stockMinimo).sort((a,b)=>a.stock-b.stock);
  $('#lowStockList').innerHTML=lows.length?lows.map(p=>`<div class="attention-item ${p.stock===0?'out':''}"><span>${p.emoji} <strong>${escapeHtml(p.nombre)}</strong></span><span>${p.stock===0?'agotado':`quedan ${p.stock}`}</span></div>`).join(''):'<div class="empty">✨ Todo está bien surtido</div>';
}

function renderSaleProducts() {
  $('#saleProducts').innerHTML=state.products.filter(p=>p.activo).map(p=>`<article class="product-card ${p.stock<=0?'sold-out':''}"><div class="product-name">${p.emoji} ${escapeHtml(p.nombre)}</div><div class="product-price">${money.format(p.precioVenta)} · quedan ${p.stock}</div><div class="stepper"><button data-sale-minus="${p.productoId}" aria-label="Quitar ${escapeHtml(p.nombre)}">−</button><strong id="sale-qty-${p.productoId}">${saleCart[p.productoId]||0}</strong><button data-sale-plus="${p.productoId}" ${p.stock<=0?'disabled':''} aria-label="Agregar ${escapeHtml(p.nombre)}">+</button></div></article>`).join('');
  $$('[data-sale-plus]').forEach(b=>b.addEventListener('click',()=>changeSaleQty(b.dataset.salePlus,1)));
  $$('[data-sale-minus]').forEach(b=>b.addEventListener('click',()=>changeSaleQty(b.dataset.saleMinus,-1)));
  updateSaleSummary();
}

function changeSaleQty(id, delta) {
  const p=state.products.find(x=>x.productoId===id); const next=Math.max(0,(saleCart[id]||0)+delta);
  if(next>p.stock) return toast(`Solo hay ${p.stock} de ${p.nombre}`,true);
  saleCart[id]=next; $(`#sale-qty-${id}`).textContent=next; updateSaleSummary();
}
function updateSaleSummary(){ const items=Object.entries(saleCart).filter(([,q])=>q>0); const count=items.reduce((s,[,q])=>s+q,0); const total=items.reduce((s,[id,q])=>s+state.products.find(p=>p.productoId===id).precioVenta*q,0); $('#saleItemCount').textContent=count; $('#saleTotal').textContent=money.format(total); $('#registerSaleBtn').textContent=`Continuar · ${money.format(total)}`; $('#registerSaleBtn').disabled=count===0; }

function registerSale(){
  const items=Object.entries(saleCart).filter(([,cantidad])=>cantidad>0);if(!items.length)return;
  const cards=[];items.forEach(([id,cantidad])=>{const p=state.products.find(x=>x.productoId===id);for(let unit=1;unit<=cantidad;unit++){const subtotal=p.precioVenta;cards.push(`<article class="payment-card" data-checkout="${id}-${unit}" data-product="${id}" data-subtotal="${subtotal}"><h3>${p.emoji} ${escapeHtml(p.nombre)}${cantidad>1?` · ${unit} de ${cantidad}`:''}</h3><div class="amount-due">${money.format(subtotal)}</div><label>¿Para quién es?<input data-client required placeholder="Nombre del cliente"></label><label>Forma de pago<select data-payment-method><option value="EFECTIVO">Efectivo</option><option value="TRANSFERENCIA">Transferencia</option><option value="PENDIENTE">No ha pagado</option><option value="MIXTO">Pago dividido o abono</option></select></label><div class="split-fields"><label>Efectivo<input data-cash type="number" min="0" max="${subtotal}" step="0.01" value="${subtotal}"></label><label>Transferencia<input data-transfer type="number" min="0" max="${subtotal}" step="0.01" value="0" disabled></label></div><div class="payment-status">Pagado: ${money.format(subtotal)} · Pendiente: ${money.format(0)}</div></article>`);}});
  openModal('Cliente y forma de pago',`<form id="checkoutForm" class="modal-form"><p class="inventory-meta">Cada unidad es una cuenta separada. Puedes asignar personas y pagos diferentes.</p>${cards.join('')}<div id="checkoutTotals" class="payment-status"></div><button class="primary-button" type="submit">Confirmar venta</button></form>`);
  $$('[data-payment-method]').forEach(s=>s.addEventListener('change',()=>updateCheckoutCard(s.closest('[data-checkout]'),true)));$$('[data-cash],[data-transfer]').forEach(i=>i.addEventListener('input',()=>updateCheckoutCard(i.closest('[data-checkout]'))));$('#checkoutForm').addEventListener('submit',submitSaleCheckout);updateCheckoutTotals();
}
function updateCheckoutCard(card,reset=false){const method=$('[data-payment-method]',card).value,subtotal=Number(card.dataset.subtotal),cash=$('[data-cash]',card),transfer=$('[data-transfer]',card);cash.disabled=method==='TRANSFERENCIA'||method==='PENDIENTE';transfer.disabled=method==='EFECTIVO'||method==='PENDIENTE';if(reset){cash.value=method==='EFECTIVO'?subtotal:0;transfer.value=method==='TRANSFERENCIA'?subtotal:0}const cashAmount=Number(cash.value||0),transferAmount=Number(transfer.value||0),paid=cashAmount+transferAmount,pending=Math.max(0,subtotal-paid),isOver=paid>subtotal+0.001,isIncomplete=(method==='EFECTIVO'||method==='TRANSFERENCIA')&&Math.abs(paid-subtotal)>0.001,isEmptyMixed=method==='MIXTO'&&paid<=0,status=$('.payment-status',card);status.textContent=isOver?`El pago supera ${money.format(subtotal)}`:isIncomplete?`Debe recibirse exactamente ${money.format(subtotal)}`:isEmptyMixed?'Captura un abono o selecciona “No ha pagado”':`Pagado: ${money.format(paid)} · Pendiente: ${money.format(pending)}`;status.classList.toggle('pending',!isOver&&pending>0);status.classList.toggle('invalid',isOver||isIncomplete||isEmptyMixed);updateCheckoutTotals()}
function updateCheckoutTotals(){const cards=$$('[data-checkout]');if(!cards.length||!$('#checkoutTotals'))return;let total=0,paid=0;cards.forEach(card=>{total+=Number(card.dataset.subtotal);paid+=Number($('[data-cash]',card).value||0)+Number($('[data-transfer]',card).value||0)});$('#checkoutTotals').textContent=`Total ${money.format(total)} · Recibido ${money.format(paid)} · Por cobrar ${money.format(Math.max(0,total-paid))}`}
async function submitSaleCheckout(e){e.preventDefault();const detalles=[];for(const card of $$('[data-checkout]')){const productoId=card.dataset.product,subtotal=Number(card.dataset.subtotal),cliente=$('[data-client]',card).value.trim(),method=$('[data-payment-method]',card).value,cash=Number($('[data-cash]',card).value||0),transfer=Number($('[data-transfer]',card).value||0),paid=cash+transfer;let pagos=[];if(!cliente)return toast('Escribe el nombre de cada cliente',true);if(cash<0||transfer<0||paid>subtotal+0.001)return toast(`No puedes recibir más de ${money.format(subtotal)}`,true);if((method==='EFECTIVO'||method==='TRANSFERENCIA')&&Math.abs(paid-subtotal)>0.001)return toast(`El pago debe ser exactamente ${money.format(subtotal)}`,true);if(method==='EFECTIVO'&&transfer>0)return toast('En efectivo no debe haber importe de transferencia',true);if(method==='TRANSFERENCIA'&&cash>0)return toast('En transferencia no debe haber importe de efectivo',true);if(method==='PENDIENTE'&&paid>0)return toast('Selecciona una forma de pago para registrar el importe',true);if(method==='MIXTO'&&paid<=0)return toast('Captura un abono o selecciona “No ha pagado”',true);if(cash>0)pagos.push({metodo:'EFECTIVO',monto:cash});if(transfer>0)pagos.push({metodo:'TRANSFERENCIA',monto:transfer});detalles.push({productoId,cantidad:1,cliente,pagos})}if(!await appConfirm(`¿Registrar la venta por ${$('#saleTotal').textContent}?`))return;setLoading(true);try{const r=await apiRequest('registerSale',{vendedor:$('#sellerSelect').value,detalles});closeModal();resetSaleForm();await refreshAll(false);historyPeriod='today';$$('#historyFilters button').forEach(b=>b.classList.toggle('active',b.dataset.period==='today'));$('#customDates').hidden=true;navigate('history');toast(r.message||'✅ Venta registrada')}catch(err){console.error(err);toast('❌ No se pudo registrar la venta.',true)}finally{setLoading(false)}}
function resetSaleForm(){saleCart={};renderSaleProducts();$('#sellerSelect').selectedIndex=0;$('#saleItemCount').textContent='0';$('#saleTotal').textContent=money.format(0);$('#registerSaleBtn').textContent=`Continuar · ${money.format(0)}`;$('#registerSaleBtn').disabled=true}

async function undoLastSale(){
  if(!await appConfirm('¿Deseas deshacer la última venta registrada?','Deshacer venta'))return; setLoading(true);
  try{const r=await apiRequest('undoLastSale');toast(r.message||'Venta cancelada e inventario recuperado');saleCart={};await refreshAll(false)}catch(e){console.error(e);toast(e.message,true)}finally{setLoading(false)}
}

function renderInventory(){
  const q=$('#inventorySearch').value.trim().toLowerCase(); const products=state.products.filter(p=>p.nombre.toLowerCase().includes(q));
  $('#inventoryProducts').innerHTML=products.length?products.map(p=>`<article class="inventory-card ${stockStatus(p)}"><div><h3>${p.emoji} ${escapeHtml(p.nombre)}</h3><div class="inventory-meta">${money.format(p.precioVenta)} · Mín. ${p.stockMinimo} · Ideal ${p.stockIdeal}<br>${statusLabel(p)}</div></div><div class="stock-value"><strong>${p.stock}</strong><span>disponibles</span><button data-adjust="${p.productoId}">Modificar</button></div></article>`).join(''):'<div class="empty">No se encontraron productos</div>';
  $$('[data-adjust]').forEach(b=>b.addEventListener('click',()=>openAdjustment(b.dataset.adjust)));
}

function openInventoryEntry(){
  openModal('Registrar mercancía',`<form id="entryForm" class="modal-form"><p class="inventory-meta">Escribe cuántas unidades llegaron. Puedes capturar varios productos.</p><div class="entry-list">${state.products.map(p=>`<label class="entry-row"><span>${p.emoji} ${escapeHtml(p.nombre)}<small class="stock-caption">Actual: ${p.stock}</small></span><input type="number" min="0" step="1" inputmode="numeric" data-entry="${p.productoId}" value="0"></label>`).join('')}</div><label><span>Pedido relacionado (opcional)</span><select id="entryOrder"><option value="">Ninguno</option>${state.orders.filter(o=>o.estado==='PEDIDO').map(o=>`<option value="${o.pedidoId}">${o.pedidoId}</option>`).join('')}</select></label><button class="primary-button" type="submit">Registrar entrada</button></form>`);
  $('#entryForm').addEventListener('submit',submitInventoryEntry);
}

async function submitInventoryEntry(e){e.preventDefault();const detalles=$$('[data-entry]',e.target).map(i=>({productoId:i.dataset.entry,cantidad:Number(i.value)})).filter(x=>x.cantidad>0);if(!detalles.length)return toast('Captura al menos una cantidad',true);if(!await appConfirm('¿Registrar la entrada de mercancía?'))return;setLoading(true);try{const r=await apiRequest('registerInventoryEntry',{detalles,pedidoId:$('#entryOrder').value||null});closeModal();toast(r.message||'Mercancía registrada');await refreshAll(false)}catch(err){console.error(err);toast(err.message,true)}finally{setLoading(false)}}

function openAdjustment(id){const p=state.products.find(x=>x.productoId===id);openModal(`Modificar ${p.nombre}`,`<form id="adjustForm" class="modal-form"><p>Existencia actual: <strong>${p.stock}</strong></p><label>Motivo<select id="adjustReason"><option value="ENTRADA">Entrada de mercancía</option><option value="AJUSTE">Ajuste</option><option value="MERMA">Merma</option><option value="MERMA">Producto dañado</option><option value="AJUSTE">Otro</option></select></label><label>Cambio de unidades<input id="adjustQty" type="number" step="1" inputmode="numeric" placeholder="Ej. 5 o -2" required></label><label>Nota<input id="adjustNote" maxlength="120" placeholder="Motivo breve"></label><button type="submit" class="primary-button">Guardar movimiento</button></form>`);$('#adjustForm').addEventListener('submit',async e=>{e.preventDefault();const cantidad=Number($('#adjustQty').value);if(!cantidad||p.stock+cantidad<0)return toast('La cantidad no es válida',true);if(!await appConfirm(`¿Cambiar el stock de ${p.stock} a ${p.stock+cantidad}?`,'Modificar inventario'))return;setLoading(true);try{await apiRequest('adjustInventory',{productoId:id,cantidad,tipo:$('#adjustReason').value,motivo:$('#adjustNote').value||$('#adjustReason option:checked').textContent});closeModal();toast('Inventario actualizado');await refreshAll(false)}catch(err){console.error(err);toast(err.message,true)}finally{setLoading(false)}})}

function openShare(){let showQty=false;const draw=()=>{const message=buildShareMessage(showQty);$('#modalBody').innerHTML=`<div class="switch-row"><strong>Mostrar cantidades</strong><label class="switch"><input id="showQty" type="checkbox" ${showQty?'checked':''}><span></span></label></div><div class="share-preview">${escapeHtml(message)}</div><div class="modal-actions"><button id="copyShare" class="secondary-button">📋 Copiar lista</button><button id="whatsappShare" class="primary-button">💬 Enviar por WhatsApp</button></div>`;$('#showQty').addEventListener('change',e=>{showQty=e.target.checked;draw()});$('#copyShare').addEventListener('click',async()=>{try{await navigator.clipboard.writeText(message);toast('Lista copiada')}catch(e){console.error(e);toast('No se pudo copiar; mantén presionado el texto.',true)}});$('#whatsappShare').addEventListener('click',()=>window.open(`https://wa.me/?text=${encodeURIComponent(message)}`,'_blank','noopener'))};openModal('Compartir existencias','');draw()}
function buildShareMessage(showQty=false){const available=state.products.filter(p=>p.activo&&p.stock>0);const troles=available.filter(p=>p.categoria==='Trol');const others=available.filter(p=>p.categoria!=='Trol');let lines=['🍧 LA MICHOACANA 🍧','','Sabores disponibles hoy:','',...troles.map(p=>`${p.emoji} ${p.nombre}${showQty?` — ${p.stock}`:''}`)];if(troles.length)lines.push('',`💲${troles[0].precioVenta} c/u`);if(others.length)lines.push('','También tenemos:',...others.map(p=>`${p.emoji} ${p.nombre}${showQty?` — ${p.stock}`:''} · ${money.format(p.precioVenta)}`));lines.push('','✨ '+state.config.mensajeWhatsApp);return lines.join('\n')}

function generarPedidoPorPresupuesto(presupuesto){orderCart={};if(!Number.isFinite(presupuesto)||presupuesto<=0){renderOrderProducts();return toast('Escribe un presupuesto mayor que cero',true)}const all=[...state.products].filter(p=>p.activo&&p.precioCompra>0),hasSales=all.some(p=>Number(p.ventasUltimos30Dias)>0),products=all.filter(p=>!hasSales||Number(p.ventasUltimos30Dias)>0).sort((a,b)=>recommendationScore(b)-recommendationScore(a));let remaining=presupuesto;for(const p of products){const desired=suggestedOrderQuantity(p,hasSales),qty=Math.min(desired,Math.floor(remaining/p.precioCompra));if(qty>0){orderCart[p.productoId]=qty;remaining-=qty*p.precioCompra}}renderOrderProducts();toast('Pedido basado en ventas de los últimos 30 días')}
function priority(p){return p.stock===0?0:p.stock<p.stockMinimo?1:p.stock<p.stockIdeal?2:3}
function recommendationScore(p){const rotation=Number(p.ventasUltimos30Dias)||0,urgency=p.stock===0?40:p.stock<p.stockMinimo?25:p.stock<p.stockIdeal?10:0;return rotation*5+urgency}
function suggestedOrderQuantity(p,hasSales=state.products.some(x=>Number(x.ventasUltimos30Dias)>0)){const rotation=Number(p.ventasUltimos30Dias)||0;if(hasSales&&rotation===0)return 0;const target=hasSales?Math.min(p.stockIdeal*2,Math.max(p.stockIdeal,Math.ceil(rotation/2))):p.stockIdeal;return Math.max(0,target-p.stock)}
function renderOrderProducts(){const hasSales=state.products.some(x=>Number(x.ventasUltimos30Dias)>0),products=[...state.products].filter(p=>p.activo&&p.precioCompra>0).sort((a,b)=>recommendationScore(b)-recommendationScore(a)||a.nombre.localeCompare(b.nombre,'es'));$('#orderProducts').innerHTML=products.map(p=>{const suggested=suggestedOrderQuantity(p,hasSales);const qty=orderCart[p.productoId]||0;return `<article class="order-card"><div><h3>${p.emoji} ${escapeHtml(p.nombre)}</h3><div class="order-meta">Actual ${p.stock} · Vendidos 30 días: ${p.ventasUltimos30Dias||0}<br>Sugerencia: comprar ${suggested} · ${money.format(p.precioCompra)} c/u</div></div><div><div class="stepper"><button data-order-minus="${p.productoId}">−</button><strong>${qty}</strong><button data-order-plus="${p.productoId}">+</button></div><div class="subtotal">${money.format(qty*p.precioCompra)}</div></div></article>`}).join('');$$('[data-order-plus]').forEach(b=>b.addEventListener('click',()=>changeOrderQty(b.dataset.orderPlus,1)));$$('[data-order-minus]').forEach(b=>b.addEventListener('click',()=>changeOrderQty(b.dataset.orderMinus,-1)));updateOrderSummary()}
function changeOrderQty(id,delta){const p=state.products.find(x=>x.productoId===id);const next=Math.max(0,(orderCart[id]||0)+delta);const budget=Number($('#budgetInput').value)||0;const current=orderTotal();if(delta>0&&current+p.precioCompra>budget)return toast('El pedido no puede exceder el presupuesto',true);orderCart[id]=next;renderOrderProducts()}
function orderTotal(){return Object.entries(orderCart).reduce((s,[id,q])=>s+state.products.find(p=>p.productoId===id).precioCompra*q,0)}
function updateOrderSummary(){const budget=Number($('#budgetInput').value)||0,total=orderTotal();$('#orderSummary').hidden=total<=0;$('#orderTotal').textContent=money.format(total);$('#orderRemaining').textContent=money.format(Math.max(0,budget-total));$('#createOrderBtn').disabled=total<=0||total>budget}
function buildOrderMessage(details){const lines=['Quisiera pedir:',''];details.filter(d=>Number(d.cantidad)>0).forEach(d=>{const p=state.products.find(x=>x.productoId===d.productoId);lines.push(`${p?.nombre||d.productoId} × ${d.cantidad}`)});return lines.join('\n')}
function shareOrderByWhatsApp(order=null){const details=order?order.detalles:Object.entries(orderCart).filter(([,cantidad])=>cantidad>0).map(([productoId,cantidad])=>({productoId,cantidad}));const total=order?Number(order.costoTotal):orderTotal();if(!details.length)return toast('El pedido está vacío',true);const message=buildOrderMessage(details,total,order?.pedidoId||'');window.open(`https://wa.me/?text=${encodeURIComponent(message)}`,'_blank','noopener')}
async function createOrder(){const presupuesto=Number($('#budgetInput').value),detalles=Object.entries(orderCart).filter(([,cantidad])=>cantidad>0).map(([productoId,cantidad])=>({productoId,cantidad}));if(orderTotal()>presupuesto)return toast('El pedido excede el presupuesto',true);if(!await appConfirm(`¿Guardar este pedido por ${money.format(orderTotal())}?`,'Guardar pedido'))return;setLoading(true);try{const r=await apiRequest('createOrder',{presupuesto,detalles,estado:'PEDIDO'});toast(r.message||'Pedido guardado');orderCart={};$('#budgetInput').value='';await refreshAll(false);renderOrderProducts()}catch(e){console.error(e);toast(e.message,true)}finally{setLoading(false)}}

function openOrders(){const html=state.orders.length?state.orders.map(o=>`<article class="history-card"><div class="history-head"><strong>${o.pedidoId}</strong><span>${dateTime.format(new Date(o.fecha))}</span></div><div class="history-items">${o.detalles.map(d=>{const p=state.products.find(x=>x.productoId===d.productoId);return `${p?.emoji||''} ${escapeHtml(p?.nombre||d.productoId)} × ${d.cantidad}<br>`}).join('')}</div><div class="history-total"><span>${o.estado}</span><span>${money.format(o.costoTotal)}</span></div><button class="whatsapp-button" data-share-order="${o.pedidoId}">💬 Enviar por WhatsApp</button>${o.estado==='PEDIDO'?`<button class="secondary-button" data-receive="${o.pedidoId}">Marcar como recibido</button>`:''}</article>`).join(''):'<div class="empty">Aún no hay pedidos</div>';openModal('Pedidos',`<div class="history-list">${html}</div>`);$$('[data-receive]').forEach(b=>b.addEventListener('click',()=>receiveOrder(b.dataset.receive)));$$('[data-share-order]').forEach(b=>b.addEventListener('click',()=>shareOrderByWhatsApp(state.orders.find(o=>o.pedidoId===b.dataset.shareOrder))))}
async function receiveOrder(id){if(!await appConfirm('¿Confirmas que recibiste todo este pedido?','Recibir pedido'))return;setLoading(true);try{await apiRequest('receiveOrder',{pedidoId:id});closeModal();toast('Pedido recibido e inventario actualizado');await refreshAll(false)}catch(e){console.error(e);toast(e.message,true)}finally{setLoading(false)}}

function renderHistory(){if(!state.sales)return;const range=getHistoryRange();const sales=state.sales.filter(s=>{const d=new Date(s.fecha);return d>=range.from&&d<=range.to});const active=sales.filter(s=>s.estado==='ACTIVA');const count=active.reduce((n,s)=>n+s.cantidadProductos,0),total=active.reduce((n,s)=>n+s.total,0);$('#historyStats').innerHTML=`<div class="stat-mini"><span>Ventas</span><strong>${active.length}</strong></div><div class="stat-mini"><span>Productos</span><strong>${count}</strong></div><div class="stat-mini"><span>Total</span><strong>${money.format(total)}</strong></div>`;$('#salesHistory').innerHTML=sales.length?sales.sort((a,b)=>new Date(b.fecha)-new Date(a.fecha)).map(s=>`<article class="history-card ${s.estado==='CANCELADA'?'cancelled':''}"><div class="history-head"><span>${dateTime.format(new Date(s.fecha))}</span><span>${escapeHtml(s.vendedor)}</span></div><div class="history-items">${s.detalles.map(d=>{const p=state.products.find(x=>x.productoId===d.productoId);return `${p?.emoji||''} ${escapeHtml(p?.nombre||d.productoId)} × ${d.cantidad} · ${escapeHtml(d.cliente||'Cliente')} <small>${d.estadoPago||'PAGADO'}${Number(d.montoPendiente)>0?` · debe ${money.format(d.montoPendiente)}`:''}</small><br>`}).join('')}</div><div class="history-total"><span>${s.estado==='CANCELADA'?'<i class="cancelled-tag">CANCELADA</i>':'Total'}</span><span>${money.format(s.total)}</span></div></article>`).join(''):'<div class="empty">No hay ventas en este periodo</div>';renderRankings(active)}
function renderReceivables(){const items=(state.receivables||[]).filter(x=>Number(x.montoPendiente)>=0.01);$('#receivablesTotal').textContent=money.format(items.reduce((n,x)=>n+Number(x.montoPendiente),0));$('#receivablesList').innerHTML=items.length?items.map(x=>{const p=state.products.find(y=>y.productoId===x.productoId);return `<div class="receivable-row"><div><b>${escapeHtml(x.cliente)}</b><small>${p?.emoji||''} ${escapeHtml(p?.nombre||x.productoId)} × ${x.cantidad}<br>${dateTime.format(new Date(x.fecha))}</small></div><strong>${money.format(x.montoPendiente)}</strong><button data-collect="${x.detalleId}">Registrar pago</button></div>`}).join(''):'<div class="empty">✨ No hay pagos pendientes</div>';$$('[data-collect]').forEach(b=>b.addEventListener('click',()=>openCollection(b.dataset.collect)))}
function openCollection(detailId){const item=state.receivables.find(x=>x.detalleId===detailId),p=state.products.find(x=>x.productoId===item.productoId);openModal(`Cobro de ${item.cliente}`,`<form id="collectionForm" class="modal-form"><p>${p?.emoji||''} ${escapeHtml(p?.nombre||item.productoId)} · Falta <strong>${money.format(item.montoPendiente)}</strong></p><label>Monto recibido<input id="collectionAmount" type="number" min="0.01" max="${item.montoPendiente}" step="0.01" value="${item.montoPendiente}" required></label><label>Forma de pago<select id="collectionMethod"><option value="EFECTIVO">Efectivo</option><option value="TRANSFERENCIA">Transferencia</option><option value="OTRO">Otro</option></select></label><label>Nota<input id="collectionNote" maxlength="120" placeholder="Opcional"></label><button class="primary-button" type="submit">Registrar abono</button></form>`);$('#collectionForm').addEventListener('submit',async e=>{e.preventDefault();const monto=Number($('#collectionAmount').value);if(monto<=0||monto>Number(item.montoPendiente)+0.001)return toast('El monto no es válido',true);if(!await appConfirm(`¿Registrar un pago de ${money.format(monto)}?`,'Registrar abono'))return;setLoading(true);try{await apiRequest('registerPayment',{detalleId:detailId,monto,metodo:$('#collectionMethod').value,nota:$('#collectionNote').value});closeModal();toast('Pago registrado');await refreshAll(false)}catch(err){console.error(err);toast(err.message,true)}finally{setLoading(false)}})}
function getHistoryRange(){const now=new Date(),end=new Date(now);end.setHours(23,59,59,999);let from=new Date(now);from.setHours(0,0,0,0);if(historyPeriod==='week'){const day=(from.getDay()+6)%7;from.setDate(from.getDate()-day)}else if(historyPeriod==='month')from=new Date(now.getFullYear(),now.getMonth(),1);else if(historyPeriod==='custom'){const a=$('#dateFrom').value,b=$('#dateTo').value;if(a)from=new Date(`${a}T00:00:00`);if(b){end.setTime(new Date(`${b}T23:59:59`).getTime())}}return{from,to:end}}
function localDateValue(date){const y=date.getFullYear(),m=String(date.getMonth()+1).padStart(2,'0'),d=String(date.getDate()).padStart(2,'0');return `${y}-${m}-${d}`}
function updateHistoryCaption(){const range=getHistoryRange(),count=state.sales.filter(s=>{const date=new Date(s.fecha);return date>=range.from&&date<=range.to}).length,labels={today:'Hoy',week:'Esta semana',month:'Este mes',custom:`${$('#dateFrom').value} al ${$('#dateTo').value}`};$('#historyRangeCaption').textContent=`Mostrando: ${labels[historyPeriod]} · ${count} ${count===1?'venta':'ventas'}`}
function renderRankings(sales){const counts={};sales.forEach(s=>s.detalles.forEach(d=>counts[d.productoId]=(counts[d.productoId]||0)+d.cantidad));const rows=state.products.map(p=>({name:p.nombre,emoji:p.emoji,count:counts[p.productoId]||0}));const make=(list)=>list.map((x,i)=>`<div class="ranking-row"><span>${i+1}</span><span>${x.emoji} ${escapeHtml(x.name)}</span><strong>${x.count}</strong></div>`).join('');$('#topProducts').innerHTML=make([...rows].sort((a,b)=>b.count-a.count).slice(0,5));$('#bottomProducts').innerHTML=make([...rows].sort((a,b)=>a.count-b.count).slice(0,5))}
function renderPeriodStatistics(){const now=new Date(),today=new Date(now);today.setHours(0,0,0,0);const week=new Date(today);week.setDate(week.getDate()-((week.getDay()+6)%7));const month=new Date(now.getFullYear(),now.getMonth(),1);const summarize=from=>{const sales=state.sales.filter(s=>s.estado==='ACTIVA'&&new Date(s.fecha)>=from);return{cantidad:sales.reduce((n,s)=>n+s.cantidadProductos,0),dinero:sales.reduce((n,s)=>n+s.total,0)}};$('#periodStatistics').innerHTML=[['Hoy',summarize(today)],['Esta semana',summarize(week)],['Este mes',summarize(month)]].map(([label,x])=>`<div><b>${label}</b><span>${x.cantidad} productos</span><strong>${money.format(x.dinero)}</strong></div>`).join('')}

function navigate(view){$$('.view').forEach(v=>v.classList.toggle('active',v.id===`view-${view}`));$$('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===view));window.scrollTo({top:0,behavior:'smooth'});if(view==='order')renderOrderProducts();if(view==='history'){renderHistory();updateHistoryCaption()}}
function openModal(title,body){$('#modalTitle').textContent=title;$('#modalBody').innerHTML=body;$('#modalBackdrop').hidden=false;document.body.style.overflow='hidden'}
function closeModal(){$('#modalBackdrop').hidden=true;document.body.style.overflow=''}
function appConfirm(message,title='Confirmar acción'){if(confirmResolver)resolveConfirmation(false);$('#confirmTitle').textContent=title;$('#confirmMessage').textContent=message;$('#confirmBackdrop').hidden=false;setTimeout(()=>$('#confirmAcceptBtn').focus(),0);return new Promise(resolve=>{confirmResolver=resolve})}
function resolveConfirmation(accepted){if(!confirmResolver)return;const resolve=confirmResolver;confirmResolver=null;$('#confirmBackdrop').hidden=true;resolve(accepted)}
function setLoading(on){$('#loading').hidden=!on;$$('button').forEach(b=>{if(on){b.dataset.wasDisabled=String(b.disabled);b.disabled=true}else if(b.dataset.wasDisabled!==undefined){b.disabled=b.dataset.wasDisabled==='true';delete b.dataset.wasDisabled}})}
let toastTimer;function toast(message,error=false){clearTimeout(toastTimer);const el=$('#toast');el.textContent=message;el.className=`toast show${error?' error':''}`;toastTimer=setTimeout(()=>el.className='toast',3000)}

function loadDemo(){const raw=localStorage.getItem(DEMO_KEY);let db=null;if(raw){try{db=JSON.parse(raw)}catch(e){console.error(e)}}if(!db)db={products:structuredClone(initialProducts),sales:[],orders:[],movements:[],config:{nombreNegocio:'La Michoacana',mensajeWhatsApp:'¡Sabor que te enamora!',moneda:'MXN'}};db.sellers=db.sellers||['Mamá','Miri','Papá','Rodrigo','Gloria'].map((nombre,i)=>({vendedorId:`VEN${i+1}`,nombre,activo:true}));db.payments=db.payments||[];db.receivables=db.sales.flatMap(s=>s.estado==='ACTIVA'?s.detalles.filter(d=>Number(d.montoPendiente)>0).map(d=>({...d,ventaId:s.ventaId,fecha:s.fecha,vendedor:s.vendedor})):[]);return db}
function saveDemo(db){localStorage.setItem(DEMO_KEY,JSON.stringify(db))}
function demoId(prefix,list,key){const day=new Date().toISOString().slice(0,10).replaceAll('-','');const n=list.filter(x=>String(x[key]).startsWith(`${prefix}-${day}`)).length+1;return `${prefix}-${day}-${String(n).padStart(4,'0')}`}
function calculateDashboard(db=state){const today=new Date();today.setHours(0,0,0,0);const sales=db.sales.filter(s=>s.estado==='ACTIVA'&&new Date(s.fecha)>=today);return{ventasHoy:sales.reduce((n,s)=>n+s.total,0),productosVendidosHoy:sales.reduce((n,s)=>n+s.cantidadProductos,0),productosDisponibles:db.products.reduce((n,p)=>n+p.stock,0),productosBajoStock:db.products.filter(p=>p.stock<=p.stockMinimo).length}}
async function demoApi(action,data){await new Promise(r=>setTimeout(r,180));const db=loadDemo();const product=id=>db.products.find(p=>p.productoId===id);const movement=(p,cantidad,tipo,referencia,motivo)=>{const old=p.stock;p.stock+=cantidad;db.movements.push({movimientoId:demoId('M',db.movements,'movimientoId'),fecha:new Date().toISOString(),productoId:p.productoId,tipo,cantidad,stockAnterior:old,stockNuevo:p.stock,referencia,motivo})};
  if(action==='getDashboard'||action==='getProducts'||action==='getInventory'){const cutoff=Date.now()-30*864e5;db.products.forEach(p=>p.ventasUltimos30Dias=db.sales.filter(s=>s.estado==='ACTIVA'&&new Date(s.fecha).getTime()>=cutoff).reduce((n,s)=>n+s.detalles.filter(d=>d.productoId===p.productoId).reduce((a,d)=>a+d.cantidad,0),0));return{success:true,data:{...db,dashboard:calculateDashboard(db)},message:''}}
  if(action==='registerSale'){for(const d of data.detalles){const p=product(d.productoId);if(!p||d.cantidad<=0||p.stock<d.cantidad)throw new Error(`Stock insuficiente de ${p?.nombre||d.productoId}`)}const ventaId=demoId('V',db.sales,'ventaId');const detalles=data.detalles.map((d,i)=>{const p=product(d.productoId),subtotal=p.precioVenta*d.cantidad,pagos=d.pagos||[],montoPagado=pagos.reduce((n,x)=>n+Number(x.monto),0),detalleId=`${ventaId}-D${i+1}`;pagos.forEach(x=>db.payments.push({pagoId:demoId('PG',db.payments,'pagoId'),fecha:new Date().toISOString(),ventaId,detalleId,cliente:d.cliente,metodo:x.metodo,monto:Number(x.monto),referencia:'VENTA',nota:''}));return{detalleId,productoId:d.productoId,cantidad:d.cantidad,precioUnitario:p.precioVenta,subtotal,cliente:d.cliente||'Cliente',estadoPago:montoPagado>=subtotal?'PAGADO':montoPagado>0?'PARCIAL':'PENDIENTE',montoPagado,montoPendiente:subtotal-montoPagado}});const sale={ventaId,fecha:new Date().toISOString(),vendedor:data.vendedor,cantidadProductos:detalles.reduce((n,d)=>n+d.cantidad,0),total:detalles.reduce((n,d)=>n+d.subtotal,0),estado:'ACTIVA',detalles};db.sales.push(sale);detalles.forEach(d=>movement(product(d.productoId),-d.cantidad,'SALIDA',ventaId,'Venta'));saveDemo(db);return{success:true,data:sale,message:'✅ Venta registrada'}}
  if(action==='registerPayment'){let detail,sale;for(const s of db.sales){const found=s.detalles.find(d=>d.detalleId===data.detalleId);if(found){detail=found;sale=s;break}}const amount=Number(data.monto);if(!detail||sale.estado!=='ACTIVA'||amount<=0||amount>detail.montoPendiente+0.001)throw new Error('El abono no es válido');detail.montoPagado+=amount;detail.montoPendiente=Math.max(0,detail.subtotal-detail.montoPagado);detail.estadoPago=detail.montoPendiente<=0.001?'PAGADO':'PARCIAL';db.payments.push({pagoId:demoId('PG',db.payments,'pagoId'),fecha:new Date().toISOString(),ventaId:sale.ventaId,detalleId:detail.detalleId,cliente:detail.cliente,metodo:data.metodo,monto:amount,referencia:'ABONO',nota:data.nota||''});saveDemo(db);return{success:true,data:detail,message:'Pago registrado'}}
  if(action==='undoLastSale'){const sale=[...db.sales].reverse().find(s=>s.estado==='ACTIVA');if(!sale)throw new Error('No hay una venta activa para deshacer');sale.estado='CANCELADA';sale.detalles.forEach(d=>movement(product(d.productoId),d.cantidad,'DEVOLUCION',sale.ventaId,'Cancelación de venta'));saveDemo(db);return{success:true,data:sale,message:'Venta cancelada e inventario recuperado'}}
  if(action==='registerInventoryEntry'){const ref=data.pedidoId||'ENTRADA-MANUAL';data.detalles.forEach(d=>{if(d.cantidad>0)movement(product(d.productoId),d.cantidad,'ENTRADA',ref,'Entrada de mercancía')});if(data.pedidoId){const o=db.orders.find(x=>x.pedidoId===data.pedidoId);if(o)o.estado='RECIBIDO'}saveDemo(db);return{success:true,data:null,message:'Mercancía registrada'}}
  if(action==='adjustInventory'){const p=product(data.productoId);if(!p||!data.cantidad||p.stock+data.cantidad<0)throw new Error('Ajuste inválido');movement(p,data.cantidad,data.tipo,'AJUSTE-MANUAL',data.motivo);saveDemo(db);return{success:true,data:p,message:'Inventario actualizado'}}
  if(action==='createOrder'){const costoTotal=data.detalles.reduce((n,d)=>n+product(d.productoId).precioCompra*d.cantidad,0);if(costoTotal>data.presupuesto)throw new Error('El pedido excede el presupuesto');const pedidoId=demoId('P',db.orders,'pedidoId');const order={pedidoId,fecha:new Date().toISOString(),presupuesto:data.presupuesto,costoTotal,estado:data.estado||'PEDIDO',detalles:data.detalles.map(d=>({...d,precioCompra:product(d.productoId).precioCompra,subtotal:product(d.productoId).precioCompra*d.cantidad}))};db.orders.push(order);saveDemo(db);return{success:true,data:order,message:'Pedido guardado'}}
  if(action==='receiveOrder'){const o=db.orders.find(x=>x.pedidoId===data.pedidoId);if(!o||o.estado!=='PEDIDO')throw new Error('El pedido no está pendiente');o.detalles.forEach(d=>movement(product(d.productoId),d.cantidad,'ENTRADA',o.pedidoId,'Pedido recibido'));o.estado='RECIBIDO';saveDemo(db);return{success:true,data:o,message:'Pedido recibido'}}
  if(action==='getSales')return{success:true,data:db.sales,message:''};if(action==='getStatistics')return{success:true,data:{},message:''};if(action==='getOrders')return{success:true,data:db.orders,message:''};throw new Error(`Acción demo no implementada: ${action}`)
}
